### PR TITLE
Updated to latest Xamarin + NuGet package + Cleanup

### PR DESCRIPTION
**Pull request by Cheesebaron**
NuGet can be found here: https://www.nuget.org/packages/jvfloatsharp/1.0.0

If you want to be owner of the package let me know your nuget username.

### CODE REVIEW

**Comment by Johan-dutoit** [comment]
Thank you for making the changes (and doing clean up).
I don't mind being dual owners, my username is johan.dutoit (well using my microsoft account to login).

**Comment by Cheesebaron** [comment]
It can't find the username johan.dutoit

**Comment by Johan-dutoit** [comment]
Perhaps just Johan?

**Comment by Johan-dutoit** [comment]
Got the email, clicked the link... failed: "Could not confirm package ownership for 'jvfloatsharp'."

**Comment by Cheesebaron** [comment]
OK, was not sure going to add you again :)

**Comment by Cheesebaron** [comment]
Can you add me as collaborator here?

**Comment by Cheesebaron** [comment]
Great. Things seem cool now. Would be awesome if we could make a unified package with @gshacles FloatTextField

**Comment by Johan-dutoit** [comment]
Agreed.  
I am actually wanting to create a Xamarin.Forms version of this, as that will trump it all.

**Comment by Cheesebaron** [comment]
Actually Android has this now with TextInputLayout in the Design support package.

**Pull request merged**
